---
name: ghactions-ci-build
on: [pull_request]

jobs:
  cmake-mingw:
    timeout-minutes: 5
    runs-on: windows-2019
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build dir
        shell: cmd
        run: mkdir ssp4c-build

      - name: Configure
        working-directory: ssp4c-build
        shell: cmd
        run: cmake -Dssp4c_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release -G"MinGW Makefiles" ..

      - name: Build
        working-directory: ssp4c-build
        shell: cmd
        run: cmake --build . --config Release --parallel 4

      - name: Test
        working-directory: ssp4c-build
        shell: cmd
        run: ctest --output-on-failure
        
  cmake-msvc2019:
    timeout-minutes: 5
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build dir
        shell: cmd
        run: mkdir ssp4c-build

      - name: Configure
        working-directory: ssp4c-build
        shell: cmd
        run: cmake -Dssp4c_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" ..

      - name: Build
        working-directory: ssp4c-build
        shell: cmd
        run: cmake --build . --config Release --parallel 4

      - name: Test
        working-directory: ssp4c-build
        shell: cmd
        run: ctest --output-on-failure
        
  cmake-ubuntu:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build dir
        shell: bash
        run: mkdir ssp4c-build

      - name: Configure
        working-directory: ssp4c-build
        shell: bash
        run: cmake -D CMAKE_CXX_FLAGS="-fsanitize=address" -D CMAKE_C_FLAGS="-fsanitize=address" -Dssp4c_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        working-directory: ssp4c-build
        shell: bash
        run: cmake --build . --config Release --parallel 4

      - name: Test
        working-directory: ssp4c-build
        shell: bash
        run: ctest --output-on-failure